/**CREATE TABLE flunet_table(
   WHOREGION TEXT,
   ITZ VARCHAR,
   COUNTRYAREATERRITORY TEXT,
   COUNTRY_CODE TEXT,
   ORIGIN_SOURCE TEXT,	
   ISO_YEAR	INT, 
   ISO_WEEK INT,
   ISO_SDATE DATE,
   SPEC_RECEIVED_NB INT,
	SPEC_PROCESSED_NB INT,
	AH1 INT,
	AH1N12009 INT,
	AH3 INT,
	AH5 INT,
	ANOTSUBTYPED INT,
	INF_A INT,
	BVIC INT,
	BYAM INT,
	BNOTDETERMINED INT,
	INF_B INT,
	INF_ALL INT,
	INF_NEGATIVE  INT,	
	ILI_ACTIVITY INT

);   **/

SELECT * FROM flunet_table;
